### ISSUE TITLE
Function

### ISSUE THREAD

**Issue by CZW0042** [sablokgaurav/miRNA_neural_network#1]
How should I define the function: preparemiRNAsML or where should I import it?

**Comment by sablokgaurav** [comment]
To define this simply use this with in the jupyter book or you can add to a new .py file and then import it and then you can use the function. Thank you.

**Comment by CZW0042** [comment]
> To define this simply use this with in the jupyter book or you can add to a new .py file and then import it and then you can use the function. Thank you.

Thank you, a following question: there seems nothing in the __init__.py file, is this the file for setting up an initial value for 'transcript_path'?

**Comment by CZW0042** [comment]
> Thank you and the init.py is just a file to initiate. You can drop that down and use directly the function in your file.

Thanks a lot, it seens that I need to give an initial value to transcript_path, do you know what should give?
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-19-293ef4508e1e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 preparemiRNAsML("/content/miRNA_neural_network/Athaliana_167_TAIR10.transcript.fa",
      2                 "/content/test.txt",
      3                 expectation_value="0.0",
      4                 upstream=100, downstream=100)

[<ipython-input-18-e50e80893df5>](https://localhost:8080/#) in preparemiRNAsML(transcripts_file, psRNATargetfile, expectation_value, upstream, downstream)
     29                 transcripts_read[i] = ""
     30                 continue
---> 31         transcripts_read[transcript_path] += i.strip()
     32     with open(psRNATargetfile, "r") as psRNA:
     33         with open(psRNATargetfile + "processed.txt", "w") as psRNAprocessed:

UnboundLocalError: local variable 'transcript_path' referenced before assignment

**Comment by CZW0042** [comment]
> i have added the usage there. The transcript file is the file path of the transcripts that you have to provide.
> 
> preparemiRNAsML("/Users/gauravsablok/Desktop/release/Athaliana_167_TAIR10.transcript.fa", "/Users/gauravsablok/Desktop/release/test.txt", expectation_value="0.0", upstream = 100, downstream=100)

Thank you.
